### PR TITLE
fix: fix table merge cell rows not work

### PR DESCRIPTION
**Pull request by woodenfish**
fix the issue Write to merged cells #17

### CODE REVIEW

**Comment by amenadiel** [comment]
@woodenfish, I've been told in #46 that further pull requests should be made against @kant2002 's fork, 

https://github.com/kant2002/xlsx-template

because he has npm publish rights and spare time to review and merge PRs.

However, for your PR to be merged you'd need to make your changes on top of current HEAD, since they were made on top of HEAD~26, several months ago.

If you don't have time anymore, I could adapt your code to run over current HEAD, but it would feel like stealing without your explicit consent.

**Comment by kant2002** [comment]
Would you mind provide either simple test case, or at least example of XLSX file and data which produce error?

**Comment by amenadiel** [comment]
@kant2002 I made a repo demonstrating the issue

https://github.com/amenadiel/xlsx-template-mergedcells

**Comment by kant2002** [comment]
Closing stale PR. If you plan continue work on this PR, please file new one.

**Pull request closed without merging**
