### PR TITLE
Fixing Defined Range Name with Sheet Name

### PR DESCRIPTION
**Pull request by adepanges**

### CODE REVIEW

**Comment by kant2002** [comment]
Can you add the test for your scenario?

**Comment by adepanges** [comment]
Hi @kant2002 Thank you for your feedback, let me my test scenario.

**Comment by adepanges** [comment]
Hi @kant2002 
my issue is to keep the defined name (exp: Print_Titles) in every sheet in a workbook, the test case is just adjusting old test case and add a new test case or what? how about you.

Thanks

**Comment by adepanges** [comment]
After I do some research about my case, I think my ref is not match with current regex
I have named range `Print_Titles` the value is `Tables!$1:$3`
Current regex in function `splitRef` is not covered it.
image
have you idea for that problem?

**Comment by kant2002** [comment]
> the test case is just adjusting old test case and add a new test case or what? 

My preference to add new test case. And make sure that both current one and new one pass. Somebody rely on current behaviour. That way we make sure that `Tables!$1:$3` and `$1:$3` both works.

**Comment by adepanges** [comment]
Sorry I revert back for `splitRange` just afraid will defect into another case, but I add in regex check into optional for [A-Z] relate into my case to set row range only.
image
also set default `col` into empty string because in next step we have this function that col do to upper case, in my case col is null then error
image

hopefully, this can be merged because I need this for my project.
Thank you

**Comment by adepanges** [comment]
Print Titles options in page setup, will be stored in defined name
image

**Comment by kant2002** [comment]
Thanks!

**Comment by adepanges-mitrais** [comment]
Thank you.
Any plan to make release in npm so we can just update it @kant2002?

**Comment by kant2002** [comment]
V 1.3.1 already released

**Comment by adepanges** [comment]
but not yet published here?
https://github.com/optilude/xlsx-template/releases

**Comment by kant2002** [comment]
Okay, I forgot about this process. It's actually on NPM

**Comment by adepanges** [comment]
Okay thank you, sorry I do have not deep knowledge about npm, so we just wait for the version to be updated into v1.3.1?
image

**Comment by kant2002** [comment]
Okay. I finally should go sleep instead of publishing. This time it is on NPM. Please check.

**Comment by adepanges** [comment]
Thanks a lot @kant2002, Sorry to bother you.

**Pull request merged**
